const EN_US_COPY = {
  'app.loading.eyebrow': 'Preparing Vantage',
  'app.loading.title': 'Checking first-run state',
  'app.loading.description': 'Loading the desktop setup contract before opening the workspace.',
  'app.nav.dashboard': 'Dashboard',
  'app.nav.action_plan': 'Action Plan',
  'app.nav.project_progress': 'Project Progress',
  'app.nav.expense_sheet': 'Expense Sheet',
  'app.nav.plots': 'Plots',
  'app.nav.system_logs': 'System Logs',
  'app.nav.face_history': 'Face History',
  'app.language.label': 'Language',
  'app.language.follow_system': 'Follow System',
  'app.language.zh_cn': 'Simplified Chinese',
  'app.language.en_us': 'English',
  'app.theme.switch_to_light': 'Switch to light theme',
  'app.theme.switch_to_dark': 'Switch to dark theme',
  'app.nav.settings': 'Settings',
  'app.footer.powered_by': '2026 Vantage | Powered by {provider}',

  'settings.title': 'Settings',
  'settings.section.general': 'General',
  'settings.section.ai_provider': 'AI Provider',
  'settings.section.voice_provider': 'Voice Provider',
  'settings.section.data_logs': 'Data & Logs',
  'settings.section.performance': 'Performance',
  'settings.section.about': 'About',
  'settings.general.language': 'Display Language',
  'settings.general.theme': 'Theme',
  'settings.general.theme_auto': 'Auto',
  'settings.general.theme_dark': 'Dark',
  'settings.general.theme_light': 'Light',
  'settings.general.launch_at_login': 'Start Vantage automatically after Windows login',
  'settings.provider.route': 'Provider Route',
  'settings.provider.base_url': 'Base URL',
  'settings.provider.api_key': 'API Key',
  'settings.provider.model': 'Model',
  'settings.provider.show_key': 'Show API key',
  'settings.provider.hide_key': 'Hide API key',
  'settings.provider.providers': 'Providers',
  'settings.provider.name': 'Name',
  'settings.provider.add': 'Add provider',
  'settings.provider.delete': 'Delete',
  'settings.provider.enable': 'Enable',
  'settings.provider.disable': 'Disable',
  'settings.provider.enabled': 'Enabled',
  'settings.provider.disabled': 'Disabled',
  'settings.provider.default': 'Default',
  'settings.provider.set_default': 'Set Default',
  'settings.provider.delete_confirm': 'Delete provider "{name}"? This only removes the local route configuration.',
  'settings.provider.refresh_models': 'Refresh Models',
  'settings.provider.refresh_success': 'Loaded {count} models.',
  'settings.provider.refresh_failed': 'Failed to refresh models: {error}',
  'settings.provider.last_refreshed': 'Last refreshed: {value}',
  'settings.provider.not_refreshed': 'Models have not been refreshed.',
  'settings.voice_provider.base_url': 'Voice Base URL',
  'settings.voice_provider.api_key': 'Voice API Key',
  'settings.voice_provider.model': 'Voice Model',
  'settings.voice_provider.endpoint_hint': 'This provider must support /audio/transcriptions.',
  'settings.voice_provider.test_hint': 'Use the chat microphone after saving to test this voice provider.',
  'settings.paths.config': 'Config',
  'settings.paths.history': 'History',
  'settings.paths.logs': 'Logs',
  'settings.paths.plots': 'Plots',
  'settings.paths.cache': 'Cache',
  'settings.paths.runtime': 'Runtime',
  'settings.paths.data': 'Data',
  'settings.paths.open': 'Open',
  'settings.paths.open_logs': 'Open Logs',
  'settings.paths.open_failed': 'Failed to open folder.',
  'settings.data_logs.migration_done': 'History imported from {path}',
  'settings.data_logs.migration_pending': 'History migration has not been recorded.',
  'settings.performance.background_mode': 'Background Mode',
  'settings.performance.balanced': 'Balanced',
  'settings.performance.prewarm': 'Prewarm',
  'settings.performance.power_saver': 'Power Saver',
  'settings.performance.action_plan_auto_generate': 'Auto-generate Action Plan on startup',
  'settings.performance.action_plan_auto_generate_hint': 'When enabled, Vantage starts the daily Action Plan run after launch.',
  'settings.about.version': 'App Version',
  'settings.about.mode': 'App Mode',
  'settings.about.backend_runtime': 'Backend Runtime',
  'settings.about.data_dir': 'Data Directory',
  'settings.about.copy_diagnostics': 'Copy Diagnostics',
  'settings.about.copied': 'Diagnostics copied.',
  'settings.about.copy_failed': 'Clipboard is unavailable. Select and copy the diagnostics manually.',
  'settings.save.button': 'Save',
  'settings.save.saving': 'Saving...',
  'settings.save.saved': 'Settings saved.',
  'settings.save.failed': 'Failed to save settings: {error}',

  'common.model': 'Model',
  'common.reasoning': 'Reasoning',
  'common.reasoning.low': 'Low',
  'common.reasoning.medium': 'Medium',
  'common.reasoning.high': 'High',
  'common.reasoning.xhigh': 'Extra High',
  'common.reasoning.max': 'Max',
  'common.reasoning.unsupported_suffix': ' (reasoning unsupported)',
  'common.first_token': 'First {value}',
  'common.speed': 'Speed {value}',
  'common.time': 'Time {value}s',
  'common.tokens': 'Tokens {value}k',
  'common.tokens_detail': 'Tokens {value}',
  'common.cache_request': 'Request cache {value}',
  'common.cache_session': 'Session cache {value}',
  'common.fast_mode': 'Fast',
  'common.fast_mode_tooltip': 'Send service_tier=priority for supported GPT proxy models.',
  'common.error_prefix': 'Error: {error}',
  'common.network_error': 'Network Error: {error}',

  'action_plan.title': 'Action Plan',
  'action_plan.subtitle': 'Daily analysis and generated plan',
  'action_plan.tab.plan': 'Plan',
  'action_plan.tab.usage': 'Usage',
  'action_plan.thinking_title': 'Reasoning',
  'action_plan.button.regenerate': 'Regenerate',
  'action_plan.button.stop': 'Stop',
  'action_plan.copy.copied': 'Copied',
  'action_plan.copy.full_input': 'Copy Full Input',
  'action_plan.copy.prompt': 'Copy Prompt',
  'action_plan.copy.reply': 'Copy Reply',
  'action_plan.execution.actual_label': 'Actual: {value}',
  'action_plan.execution.actual_tooltip': 'This request used the selected model and route.',
  'action_plan.execution.fallback_label': 'Fallback: {value}',
  'action_plan.execution.fallback_tooltip': 'The requested model or route was unavailable, so the backend used a fallback runtime.',
  'action_plan.panel.analysis': 'General Analysis',
  'action_plan.panel.today_plan': "Today's Plan",
  'action_plan.placeholder.welcome.title': 'Action Plan is ready',
  'action_plan.placeholder.welcome.body': 'Load today\'s context or start a new generation when you are ready.',
  'action_plan.placeholder.connecting.title': 'Connecting to backend',
  'action_plan.placeholder.connecting.body': 'Loading the latest plan state and available models.',
  'action_plan.placeholder.load_failed.title': 'Failed to load today\'s plan',
  'action_plan.placeholder.load_failed.body': 'The backend response could not be read. Check the service logs and try again.',
  'action_plan.placeholder.analysis_unavailable.title': 'Analysis unavailable',
  'action_plan.placeholder.analysis_unavailable.body': 'No saved analysis content was returned for today.',
  'action_plan.placeholder.waiting.title': 'Waiting to generate today\'s plan',
  'action_plan.placeholder.waiting.body': 'Choose a model and start when you are ready.',
  'action_plan.placeholder.waiting_analysis.title': 'Waiting for analysis to finish',
  'action_plan.placeholder.waiting_analysis.body': 'The plan panel will continue after the analysis stream is ready.',
  'action_plan.placeholder.analyzing.title': 'Analyzing data',
  'action_plan.placeholder.analyzing.body': 'Streaming analysis output...',
  'action_plan.placeholder.plan_unavailable.title': 'Plan unavailable',
  'action_plan.placeholder.plan_unavailable.body': 'No saved plan content was returned for today.',
  'action_plan.placeholder.stopped': 'Generation stopped. You can start again at any time.',
  'action_plan.render.corrupted': 'The markdown output is partially corrupted. Showing plain text fallback.',
  'action_plan.render.empty': 'No content yet.',

  'chat.header.title': 'Chat',
  'chat.input_placeholder': 'Type a message...',
  'chat.default_model': 'Select a model',
  'chat.provider_unavailable': 'Provider unavailable',
  'chat.powered_by': 'Powered by {provider}',
  'chat.cache_route_warning': 'Different route: cache will not be reused across providers or models.',
  'chat.clear': 'Clear',
  'chat.clear_title': 'Clear chat history',
  'chat.clear_confirm': 'Clear the visible chat history?',
  'chat.clear_failed': 'Failed to clear chat: {error}',
  'chat.reasoning_title': 'Reasoning',
  'chat.thinking': 'Thinking...',
  'chat.empty.with_context': 'Ask about the current workspace context.',
  'chat.empty.without_context': 'Start a new conversation.',
  'chat.empty.followup': 'You can continue directly from the embedded context.',
  'chat.empty.try_input': 'Try typing a question or recording your voice.',
  'chat.record.start': 'Start recording',
  'chat.record.stop': 'Stop recording',
  'chat.record.short_start': 'Rec',
  'chat.record.short_stop': 'Stop',
  'chat.record.active': 'Recording {value}',
  'chat.role.user': 'You',
  'chat.role.assistant': 'AI',
  'chat.send_short': 'Send',
  'chat.voice_model': 'Voice model: {model}',
  'chat.transcribing': 'Transcribing...',
  'chat.transcription_failed': 'No speech recognized. Please try again.',
  'chat.transcription_error': 'Transcription failed: {error}',
  'chat.voice_config_error': 'Voice transcription is not configured. Current model: {model}. Open Settings > Voice Provider.',
  'chat.microphone_error': 'Failed to access the microphone: {error}',

  'dashboard.title': 'System Dashboard',
  'dashboard.open_photos': 'Open Photos',
  'dashboard.open_screenshots': 'Open Screenshots',
  'dashboard.latest_photo': 'Latest Photo',
  'dashboard.latest_screenshot': 'Latest Screenshot',
  'dashboard.latest_photo_alt': 'Latest local photo preview',
  'dashboard.latest_screenshot_alt': 'Latest desktop screenshot preview',
  'dashboard.media.show': 'Show media',
  'dashboard.media.hide': 'Hide media',
  'dashboard.media.hidden': 'Media hidden for privacy',
  'dashboard.media.hidden_detail': 'Reveal only when you need to inspect the latest capture.',
  'dashboard.camera_feed': 'Camera Feed',
  'dashboard.no_data': 'No Data',
  'dashboard.stat.cpu_usage': 'CPU Usage',
  'dashboard.stat.memory': 'Memory',
  'dashboard.stat.memory_used': '{percent}% Used',
  'dashboard.stat.disk_free': 'Disk Free',
  'dashboard.stat.days_left': '~{value} Days left',
  'dashboard.stat.storage_used': 'Storage Used',
  'dashboard.stat.group_size': '~{value} MB/group',
  'dashboard.stat.air_quality': 'Air Quality (US)',
  'dashboard.stat.loading': 'Loading...',
  'dashboard.stat.focus_time': 'Focus Time',
  'dashboard.stat.away': 'Away',
  'dashboard.stat.limit': 'Limit: {value} min',
  'dashboard.stat.timer_paused': 'Timer paused',
  'dashboard.alert.open_folder_failed': 'Failed to open folder: {error}',
  'dashboard.alert.network_error': 'Network error or server unreachable',
  'camera_feed.live_stream_alt': 'Live camera stream',
  'camera_feed.ready': 'Camera ready',
  'camera_feed.show_stream': 'Camera hidden for privacy',
  'camera_feed.disconnected': 'Camera disconnected',
  'camera_feed.disable_detection': 'Disable person detection',
  'camera_feed.enable_detection': 'Enable person detection',
  'camera_feed.detecting': 'Detecting',
  'camera_feed.detection_off': 'Off',
  'camera_feed.live': 'Live',
  'camera_feed.ready_short': 'Ready',
  'camera_feed.offline': 'Offline',

  'expense.title': 'Expense Sheet',
  'expense.file': 'File',
  'expense.source': 'Source',
  'expense.updated': 'Updated',
  'expense.sheets': 'Sheets',
  'expense.file_fallback': 'Balance Sheet.xlsx',
  'expense.refresh': 'Refresh',
  'expense.refreshing': 'Refreshing...',
  'expense.loading': 'Loading expense data...',
  'expense.snapshot_kicker': 'Snapshot',
  'expense.snapshot_title': 'Current Financial Snapshot',
  'expense.snapshot_description': 'The figures above use the latest valid records before the app runtime, acting as the summary entry for the trend card below.',
  'expense.kpi.cash_and_stock': 'Cash and equivalents',
  'expense.kpi.daily_burn': 'Recent daily spending',
  'expense.kpi.required_budget': 'Required monthly budget',
  'expense.kpi.coverage_days': 'Cash coverage days',
  'expense.kpi_hint.cash_and_stock': 'Based on the latest assets within the visible time window.',
  'expense.kpi_hint.daily_burn': 'Backfilled from the nearest valid record before the current runtime.',
  'expense.kpi_hint.required_budget': 'Aggregated from the budget sheet and unaffected by future spending rows.',
  'expense.kpi_hint.coverage_days': 'Estimated from the latest assets and recent daily average spending.',
  'expense.chart_eyebrow': 'expense sheet',
  'expense.balance_chart_title': 'Assets and spending trend',
  'expense.balance_chart_description': 'Bring total assets, account-level assets, and daily spending back into the Expense Sheet view to see movement and pressure together.',
  'expense.balance_chart_unavailable': 'The assets and spending chart is unavailable for now.',
  'expense.forecast_title': 'Future Income Forecast',
  'expense.forecast_desc': 'Planned rows are separated from actual history, so future income is visible without distorting current spending.',
  'expense.forecast_range': 'Forecast window',
  'expense.forecast_range_hint': '{count} months',
  'expense.forecast_fixed_income': 'Fixed monthly income',
  'expense.forecast_fixed_income_hint': 'Base income filled through the graduation month.',
  'expense.forecast_extra_income': 'Extra monthly income',
  'expense.forecast_total_income': 'Total monthly income',
  'expense.forecast_planned_spend': 'Planned monthly spend',
  'expense.forecast_net_cash_flow': 'Planned monthly net cash flow',
  'expense.forecast_projected_balance': 'Projected ending cash + stock',
  'expense.error.load_chart': 'Failed to load the balance chart',
  'expense.error.load_sheet': 'Failed to load the expense sheet',
  'expense.error.chart_not_found': 'Assets and spending chart not found',
  'expense.error.generic': 'Failed to load expense data',
  'expense.recent_spending': 'Recent Spending',
  'expense.recent_spending_desc': 'Show the latest rows with spending, notes, or reimbursement details first.',
  'expense.period_spend': 'Period spend {value}',
  'expense.daily_average': 'Daily avg {value}',
  'expense.large_spend': 'Large spend: {value}',
  'expense.income_note': 'Income note: {value}',
  'expense.no_recent_spending': 'No recent spending records to show.',
  'expense.budget_structure': 'Budget Structure',
  'expense.budget_structure_desc': 'Split required and optional budget, then summarize by category.',
  'expense.monthly_required': 'Monthly required',
  'expense.monthly_optional': 'Monthly optional',
  'expense.per_month': '/ month',
  'expense.no_budget': 'No available budget items in the workbook yet.',
  'expense.high_value_assets': 'High-Value Assets',
  'expense.high_value_assets_desc': 'Keep assets above RMB 1000 so the list reads like an inventory instead of an accounting table.',
  'expense.quantity_price': 'Qty {quantity} · Unit {price}',
  'expense.total': 'Total',
  'expense.no_assets': 'No high-value assets recorded yet.',
  'expense.social': 'Social Spending',
  'expense.social_desc': 'This is event-driven spending, so a compact list works better than a full table.',
  'expense.no_date': 'No date recorded',
  'expense.no_social': 'No social spending records yet.',
  'expense.tips': 'Spending Tips',
  'expense.tips_desc': 'Keep suggestions visible, but demote them into supporting context instead of headline KPIs.',
  'expense.no_tips': 'No extra suggestions right now.',
  'expense.raw_sheets': 'Raw Sheets',
  'expense.raw_sheets_desc': 'Keep the original workbook as a detail view and inspect one sheet at a time.',
  'expense.raw_sheets_aria': 'Raw workbook sheets',
  'expense.raw_sheet_rows': '{count} rows{suffix}',
  'expense.raw_sheet_truncated': ' (truncated)',
  'expense.days_value': '{value} days',
  'expense.more_items': '+ {count} more items',

  'plots.section.health.title': 'Health Primary View',
  'plots.section.health.desc': 'Lead with weight, body fat, and time layout so health imbalance shows up first.',
  'plots.section.performance.title': 'Training and Behavior',
  'plots.section.performance.desc': 'Combine running trends with HHH rhythm so effort and recovery are easier to compare.',
  'plots.section.other.title': 'Other Charts',
  'plots.section.other.desc': 'Keep ungrouped charts visible so data does not disappear.',
  'plots.generated_none': 'Not generated',
  'plots.warning.title': 'Anomalous source data detected and the related charts are flagged',
  'plots.warning.body': 'Fix the source workbook first, then run Refresh charts again. Until then, warnings stay attached to those charts.',
  'plots.warning.fallback_title': 'Anomalous data',
  'plots.warning.jump': 'Jump to {chartId}',
  'plots.warning.show_details': 'Show {count} more warnings',
  'plots.warning.hide_details': 'Hide warning details',
  'plots.inline_warning.title': 'Some extracted rows are incomplete and may create gaps in this chart',
  'plots.inline_warning.detail_fallback': 'Please inspect the source data',
  'plots.inline_warning.remaining': '{count} more rows are hidden here. See the top warning panel.',
  'plots.chart.primary': 'primary chart',
  'plots.chart.support': 'support chart',
  'plots.chart.warning': 'warning',
  'plots.empty_chart': 'No chart data available',
  'plots.hero.chip': 'plots dashboard',
  'plots.hero.title': 'Prioritize the charts that matter most for health before supporting analysis',
  'plots.hero.desc': 'This page is reordered by information priority: overview and anomalies first, primary weight and schedule charts next, then training, HHH, and finance further down.',
  'plots.refresh': 'Refresh charts',
  'plots.refreshing': 'Refreshing...',
  'plots.summary.chart_count': 'Charts',
  'plots.summary.section_count': 'Sections',
  'plots.summary.warning_count': 'Warnings',
  'plots.summary.generated_at': 'Generated',
  'plots.error_title': 'Failed to load charts',
  'plots.error_load': 'Failed to load charts.',
  'plots.empty': 'No chart data available to display.',

  'project_progress.loading': 'Loading project momentum...',
  'project_progress.error.title': 'Error Loading Data',
  'project_progress.error.body': 'Failed to load project progress. Make sure the backend is running.',
  'project_progress.retry': 'Retry',
  'project_progress.title': 'Project Momentum',
  'project_progress.refresh': 'Refresh Data',
  'project_progress.active_focus': 'Active Focus (TODOs)',
  'project_progress.no_pending': 'No pending tasks found. You\'re all caught up!',
  'project_progress.overall_momentum': 'Overall Momentum',
  'project_progress.completed': 'Completed',
  'project_progress.total_tasks': 'Total Tracked Tasks:',
  'project_progress.completed_tasks': 'Completed Tasks:',
  'project_progress.pending_tasks': 'Pending Tasks:',
  'project_progress.recent_milestone': 'Recently Completed Milestone',
  'project_progress.no_completed': 'No completed tasks yet.',
  'project_progress.recent_activity': 'Recent Activity (14 Days)',
  'project_progress.no_commits': 'No recent commits found in the last 14 days.',

  'system_logs.title': 'System Monitor Logs',
  'system_logs.subtitle': 'Real-time backend event stream',
  'system_logs.empty': 'No log lines yet.',
  'system_logs.pause': 'Pause',
  'system_logs.resume': 'Resume',
  'system_logs.copy_visible': 'Copy visible',
  'system_logs.copied': 'Visible logs copied.',
  'system_logs.copy_failed': 'Clipboard is unavailable.',
  'system_logs.search_placeholder': 'Search visible logs',
  'system_logs.filter.all': 'All',
  'system_logs.filter.error': 'Errors',
  'system_logs.filter.warning': 'Warnings',
  'system_logs.filter.info': 'Info',

  'usage.title': 'Usage Dashboard',
  'usage.subtitle': 'Historical model consumption from recorded sessions',
  'usage.window.all_time': 'All recorded calls',
  'usage.refresh': 'Refresh',
  'usage.error.load': 'Failed to load usage dashboard.',
  'usage.loading': 'Loading usage dashboard...',
  'usage.empty': 'No model usage recorded yet.',
  'usage.overview': 'Usage Overview',
  'usage.total_caption': 'Total model tokens recorded across tracked sessions',
  'usage.latest_activity': 'Latest Activity',
  'usage.prompt_share': 'Prompt Share',
  'usage.completion_share': 'Completion Share',
  'usage.summary.total_tokens': 'Total Tokens',
  'usage.summary.prompt_tokens': 'Prompt Tokens',
  'usage.summary.completion_tokens': 'Completion Tokens',
  'usage.summary.completion_rate': 'Completion tok/s',
  'usage.summary.total_rate': 'Total tok/s',
  'usage.summary.cache_hit': 'Cache Hit',
  'usage.summary.cache_hit_rate': 'Cache Hit Rate',
  'usage.summary.reasoning_tokens': 'Reasoning Tokens',
  'usage.summary.active_sources': 'Active Sources',
  'usage.summary.prompt_split': '{prompt} prompt / {completion} completion',
  'usage.summary.percent_of_total': '{value} of total tokens',
  'usage.summary.completion_duration': 'Completion tokens / duration',
  'usage.summary.total_duration': 'Prompt + completion / duration',
  'usage.summary.cache_split': '{hit} hit / {miss} miss',
  'usage.summary.cache_hit_rate_detail': 'Cached prompt token share',
  'usage.summary.reasoning_tokens_detail': 'Thinking tokens reported by provider',
  'usage.summary.recorded_sessions': '{value} recorded sessions',
  'usage.by_source': 'By Source',
  'usage.by_source.empty': 'No source usage yet.',
  'usage.source.total': '{value} total',
  'usage.source.sessions': '{value} sessions',
  'usage.source.completed': '{value} completed',
  'usage.source.failed': '{value} failed',
  'usage.source.duration': 'Duration {value}',
  'usage.source.prompt_share': 'Prompt Share {value}',
  'usage.source.completion_share': 'Completion Share {value}',
  'usage.speed_trend.title': 'Speed Trend',
  'usage.speed_trend.subtitle': 'Per-call model throughput from completed calls',
  'usage.speed_trend.axis_note': 'Fast models may use the right axis; tooltips keep real values.',
  'usage.speed_trend.empty': 'No completed calls with duration yet.',
  'usage.speed_trend.output_rate': 'Completion tok/s',
  'usage.speed_trend.total_rate': 'Total tok/s',
  'usage.speed_trend.high_speed_axis': 'High-speed tok/s',
  'usage.speed_trend.tooltip_source': 'Source',
  'usage.speed_trend.tooltip_provider': 'Provider',
  'usage.speed_trend.tooltip_reasoning': 'Reasoning',
  'usage.speed_trend.tooltip_service_tier': 'Service Tier',
  'usage.speed_trend.tooltip_duration': 'Duration',
  'usage.speed_trend.tooltip_tokens': 'Tokens',
  'usage.speed_trend.tooltip_cache': 'Cache',
  'usage.speed_trend.tooltip_reasoning_tokens': 'Reasoning Tokens',
  'usage.daily': 'Daily Usage',
  'usage.daily.empty': 'No daily usage yet.',
  'usage.daily.completed_failed': '{completed} completed / {failed} failed',
  'usage.recent_sessions': 'Recent Sessions',
  'usage.recent_sessions.empty': 'No recent sessions yet.',
  'usage.recent_calls': 'Recent Calls',
  'usage.recent_calls.empty': 'No recent calls yet.',
  'usage.cache_scope.session_total': 'Session cumulative',
  'usage.cache_scope.single_request': 'Single request',
  'usage.label.prompt': 'Prompt',
  'usage.label.completion': 'Completion',
  'usage.label.total': 'Total',
  'usage.label.cache_hit': 'Cache Hit',
  'usage.label.cache_miss': 'Cache Miss',
  'usage.label.cache_hit_rate': 'Cache Hit Rate',
  'usage.label.reasoning_tokens': 'Reasoning Tokens',
  'usage.label.service_tier': 'Service Tier',
  'usage.label.not_recorded': 'Not recorded',
  'usage.label.completion_rate': 'Completion tok/s',
  'usage.label.total_rate': 'Total tok/s',
  'usage.label.total_rate_hint': 'Includes prompt and completion tokens over request duration.',
  'usage.label.share': 'Share',
  'usage.label.prompt_share': 'Prompt Share',
  'usage.label.completion_share': 'Completion Share',
  'usage.label.session': 'Session',
  'usage.label.source': 'Source',
  'usage.label.completed': 'Completed',
  'usage.label.failed': 'Failed',
  'usage.label.last_status': 'Last Status',
  'usage.label.last_call': 'Last Call',
  'usage.label.call': 'Call',
  'usage.label.status': 'Status',
  'usage.label.model': 'Model',
  'usage.label.provider': 'Provider',
  'usage.label.duration': 'Duration',
  'usage.label.started': 'Started',
  'usage.label.unknown': 'unknown',
  'usage.status.completed': 'Completed',
  'usage.status.failed': 'Failed',
  'usage.status.ignored': 'No usage',
  'usage.status.started': 'Started',
  'usage.status.unknown': 'Unknown',

  'face_history.title': 'Face Dark Circles History',
  'face_history.subtitle': 'Live pulse uses camera scores. Historical charts use saved-photo samples.',
  'face_history.camera_online': 'Online',
  'face_history.camera_offline': 'Offline',
  'face_history.waiting_samples': 'Waiting for passing live dark-circle samples',
  'face_history.camera_offline_message': 'Camera offline',
  'face_history.live_camera_score': 'Live camera score',
  'face_history.live_pulse': 'Real-time Dark Circle Pulse',
  'face_history.latest_score': 'Latest Score',
  'face_history.latest_time': 'Latest Time',
  'face_history.camera': 'Camera',
  'face_history.samples': 'Samples',
  'face_history.trend_window': 'Trend window',
  'face_history.average': 'Average',
  'face_history.no_trend': 'No trend data',
  'face_history.live_chart_aria': 'Live dark-circle score chart',
  'face_history.trend_chart_aria': '{title} dark-circle trend chart',
  'face_history.trend.day': 'Last 24 Hours',
  'face_history.trend.week': 'Last 7 Days',
  'face_history.trend.month': 'Last 30 Days',
  'face_history.trend.all': 'All History',
  'face_history.no_image': 'No image',
  'face_history.score': 'Score: {value}',
  'face_history.load_timeout': 'Request timed out while loading the latest report.',
  'face_history.analysis_failed': 'Face analysis failed.',
  'face_history.export_failed': 'Export failed: {error}',
  'face_history.unknown_error': 'Unknown error',
  'face_history.error_prefix': 'Error: {error}',
  'face_history.loading_report': 'Loading face analysis report...',
  'face_history.empty_title': 'No analysis report yet.',
  'face_history.empty_body': 'Click Analyze Now to generate the first cached face report.',
  'face_history.lightest': 'Lightest (Best Condition)',
  'face_history.heaviest': 'Heaviest (Worst Condition)',
  'face_history.analyzing': 'Analyzing...',
  'face_history.analyze_now': 'Analyze Now',
  'face_history.export_excel': 'Export Excel',

  'onboarding.progress': 'Step {current} / {total}',
  'onboarding.button.back': 'Back',
  'onboarding.button.continue': 'Continue',
  'onboarding.button.finish': 'Finish Setup',
  'onboarding.button.skip_chat': 'Skip Chat Setup',
  'onboarding.button.choose_folder': 'Choose Folder',
  'onboarding.field.display_language': 'Display Language',
  'onboarding.field.provider_route': 'Provider Route',
  'onboarding.field.api_base_url': 'API Base URL',
  'onboarding.field.api_base_url_hint': 'Saved now for onboarding. Real runtime routing will start using it in later steps.',
  'onboarding.field.api_key': 'API Key',
  'onboarding.field.model': 'Model',
  'onboarding.field.launch_at_login': 'Start Vantage automatically after Windows login',
  'onboarding.field.import_legacy': 'Import existing history into the packaged app data directory',
  'onboarding.field.selected_folder': 'Selected folder',
  'onboarding.field.no_folder_selected': 'No folder selected yet.',
  'onboarding.provider.openai': 'OpenAI-compatible',
  'onboarding.provider.gemini': 'Gemini-compatible',
  'onboarding.provider.custom': 'Custom provider',
  'onboarding.welcome.eyebrow': 'First Run',
  'onboarding.welcome.title': 'Welcome to Vantage',
  'onboarding.welcome.description': 'This setup flow prepares the packaged app experience: user settings, provider configuration, and history import all move out of the source tree.',
  'onboarding.welcome.bullet_1': 'Review what the packaged runtime will keep under the user data directory.',
  'onboarding.welcome.bullet_2': 'Configure the chat provider or explicitly skip it for now.',
  'onboarding.welcome.bullet_3': 'Import old history from the current repo only once, then keep using the packaged copy.',
  'onboarding.provider.eyebrow': 'Chat Setup',
  'onboarding.provider.title': 'Connect the chat provider',
  'onboarding.provider.description': 'These fields are now saved into providers.json and settings.json. Real backend consumption comes later, but the onboarding flow already persists the values.',
  'onboarding.provider.bullet_1': 'Provider Route, API Base URL, API Key, and Model are all stored in user config.',
  'onboarding.provider.bullet_2': 'Launch-at-login preference is stored here and applied in the installer step later.',
  'onboarding.provider.bullet_3': 'You can still skip chat setup and finish onboarding without blocking the rest of the app.',
  'onboarding.migration.eyebrow': 'Data Import',
  'onboarding.migration.title': 'Import legacy history into packaged data',
  'onboarding.migration.description': 'Choose whether to pull the old history folder into the packaged app data directory. The migration is recorded once and the same source will not be imported twice.',
  'onboarding.migration.bullet_1': 'Only history and state files are copied here.',
  'onboarding.migration.bullet_2': 'Large photo and screenshot libraries stay where they already live.',
  'onboarding.migration.bullet_3': 'If the same legacy source was already imported, this step reuses the previous migration record.',
  'onboarding.complete.eyebrow': 'Finish',
  'onboarding.complete.title': 'Write onboarding state and open the app',
  'onboarding.complete.description': 'The final step saves onboarding_completed, provider settings, and optional migration state. After that the main workspace opens directly on next launch.',
  'onboarding.complete.bullet_1': 'settings.json records onboarding, launch-at-login, and display language preference.',
  'onboarding.complete.bullet_2': 'providers.json records the provider selection and credentials you entered.',
  'onboarding.complete.bullet_3': 'migration-state.json records where old history came from and when it was imported.',
  'onboarding.complete.summary_title': 'What will be saved',
  'onboarding.complete.summary_language': 'Display language',
  'onboarding.complete.summary_chat': 'Chat setup',
  'onboarding.complete.summary_chat_skipped': 'Skipped for now',
  'onboarding.complete.summary_legacy_import': 'Legacy import',
  'onboarding.complete.summary_legacy_yes': 'Enabled',
  'onboarding.complete.summary_legacy_no': 'Skipped',
  'onboarding.error.finish_failed': 'Failed to finish onboarding.',
};

const ZH_CN_COPY = {
  'app.loading.eyebrow': '正在准备 Vantage',
  'app.loading.title': '正在检查首次启动状态',
  'app.loading.description': '打开工作区前，先加载桌面端的初始化配置。',
  'app.nav.dashboard': '仪表盘',
  'app.nav.action_plan': '行动计划',
  'app.nav.project_progress': '项目进展',
  'app.nav.expense_sheet': '开销表',
  'app.nav.plots': '图表',
  'app.nav.system_logs': '系统日志',
  'app.nav.face_history': '黑眼圈历史',
  'app.language.label': '显示语言',
  'app.language.follow_system': '跟随系统',
  'app.language.zh_cn': '简体中文',
  'app.language.en_us': 'English',
  'app.theme.switch_to_light': '切换到浅色主题',
  'app.theme.switch_to_dark': '切换到深色主题',
  'app.nav.settings': '设置',
  'app.footer.powered_by': '2026 Vantage | 由 {provider} 驱动',

  'settings.title': '设置',
  'settings.section.general': '通用',
  'settings.section.ai_provider': 'AI 服务',
  'settings.section.voice_provider': '语音转写服务',
  'settings.section.data_logs': '数据与日志',
  'settings.section.performance': '性能',
  'settings.section.about': '关于',
  'settings.general.language': '显示语言',
  'settings.general.theme': '主题',
  'settings.general.theme_auto': '自动',
  'settings.general.theme_dark': '深色',
  'settings.general.theme_light': '浅色',
  'settings.general.launch_at_login': 'Windows 登录后自动启动 Vantage',
  'settings.provider.route': '服务路由',
  'settings.provider.base_url': 'Base URL',
  'settings.provider.api_key': 'API Key',
  'settings.provider.model': '模型',
  'settings.provider.show_key': '显示 API Key',
  'settings.provider.hide_key': '隐藏 API Key',
  'settings.provider.providers': '供应商',
  'settings.provider.name': '名称',
  'settings.provider.add': '新增供应商',
  'settings.provider.delete': '删除',
  'settings.provider.enable': '启用',
  'settings.provider.disable': '停用',
  'settings.provider.enabled': '已启用',
  'settings.provider.disabled': '已停用',
  'settings.provider.default': '默认',
  'settings.provider.set_default': '设为默认',
  'settings.provider.delete_confirm': '删除服务 "{name}"？这只会移除本地路由配置。',
  'settings.provider.refresh_models': '刷新模型',
  'settings.provider.refresh_success': '已加载 {count} 个模型。',
  'settings.provider.refresh_failed': '刷新模型失败：{error}',
  'settings.provider.last_refreshed': '上次刷新：{value}',
  'settings.provider.not_refreshed': '还没有刷新模型。',
  'settings.voice_provider.base_url': '语音 Base URL',
  'settings.voice_provider.api_key': '语音 API Key',
  'settings.voice_provider.model': '语音模型',
  'settings.voice_provider.endpoint_hint': '这个 Provider 必须支持 /audio/transcriptions。',
  'settings.voice_provider.test_hint': '保存后可回到聊天麦克风测试这个语音服务。',
  'settings.paths.config': '配置',
  'settings.paths.history': '历史',
  'settings.paths.logs': '日志',
  'settings.paths.plots': '图表',
  'settings.paths.cache': '缓存',
  'settings.paths.runtime': '运行时',
  'settings.paths.data': '数据',
  'settings.paths.open': '打开',
  'settings.paths.open_logs': '打开日志',
  'settings.paths.open_failed': '打开目录失败。',
  'settings.data_logs.migration_done': '历史已从 {path} 导入',
  'settings.data_logs.migration_pending': '还没有记录历史迁移。',
  'settings.performance.background_mode': '后台策略',
  'settings.performance.balanced': '均衡',
  'settings.performance.prewarm': '预热',
  'settings.performance.power_saver': '省电',
  'settings.performance.action_plan_auto_generate': '启动时自动生成行动计划',
  'settings.performance.action_plan_auto_generate_hint': '开启后，应用启动后会自动开始每日行动计划生成。',
  'settings.about.version': '应用版本',
  'settings.about.mode': '应用模式',
  'settings.about.backend_runtime': '后端运行时',
  'settings.about.data_dir': '数据目录',
  'settings.about.copy_diagnostics': '复制诊断信息',
  'settings.about.copied': '诊断信息已复制。',
  'settings.about.copy_failed': '剪贴板不可用，请手动选择并复制诊断信息。',
  'settings.save.button': '保存',
  'settings.save.saving': '保存中...',
  'settings.save.saved': '设置已保存。',
  'settings.save.failed': '保存设置失败：{error}',

  'common.model': '模型',
  'common.reasoning': '推理强度',
  'common.reasoning.low': '低',
  'common.reasoning.medium': '中',
  'common.reasoning.high': '高',
  'common.reasoning.xhigh': '超高',
  'common.reasoning.max': '最高',
  'common.reasoning.unsupported_suffix': '（不支持思考参数）',
  'common.first_token': '首字 {value}',
  'common.speed': '速度 {value}',
  'common.time': '耗时 {value}秒',
  'common.tokens': 'Token {value}k',
  'common.tokens_detail': 'Token {value}',
  'common.cache_request': '本次缓存 {value}',
  'common.cache_session': '会话缓存 {value}',
  'common.fast_mode': '快速',
  'common.fast_mode_tooltip': '对支持的 GPT 反代模型发送 service_tier=priority。',
  'common.error_prefix': '错误：{error}',
  'common.network_error': '网络错误：{error}',

  'action_plan.title': '行动计划',
  'action_plan.subtitle': '每日分析与计划生成',
  'action_plan.tab.plan': '计划',
  'action_plan.tab.usage': '用量',
  'action_plan.thinking_title': '推理过程',
  'action_plan.button.regenerate': '重新生成',
  'action_plan.button.stop': '停止',
  'action_plan.copy.copied': '已复制',
  'action_plan.copy.full_input': '复制完整输入',
  'action_plan.copy.prompt': '复制提示词',
  'action_plan.copy.reply': '复制回复',
  'action_plan.execution.actual_label': '实际执行：{value}',
  'action_plan.execution.actual_tooltip': '本次请求按你当前选择的模型和路由执行。',
  'action_plan.execution.fallback_label': '回退执行：{value}',
  'action_plan.execution.fallback_tooltip': '所选模型或路由不可用，后端已自动使用回退运行链。',
  'action_plan.panel.analysis': '总体分析',
  'action_plan.panel.today_plan': '今日计划',
  'action_plan.placeholder.welcome.title': '行动计划已就绪',
  'action_plan.placeholder.welcome.body': '你可以先加载今天的上下文，也可以直接开始新一轮生成。',
  'action_plan.placeholder.connecting.title': '正在连接后端',
  'action_plan.placeholder.connecting.body': '正在加载最新计划状态和可用模型。',
  'action_plan.placeholder.load_failed.title': '今日计划加载失败',
  'action_plan.placeholder.load_failed.body': '后端返回内容无法解析，请检查服务日志后重试。',
  'action_plan.placeholder.analysis_unavailable.title': '分析内容不可用',
  'action_plan.placeholder.analysis_unavailable.body': '今天没有返回可读取的分析内容。',
  'action_plan.placeholder.waiting.title': '等待生成今日计划',
  'action_plan.placeholder.waiting.body': '选择模型后即可开始。',
  'action_plan.placeholder.waiting_analysis.title': '等待分析完成',
  'action_plan.placeholder.waiting_analysis.body': '分析流准备好后，计划面板会继续输出。',
  'action_plan.placeholder.analyzing.title': '正在分析数据',
  'action_plan.placeholder.analyzing.body': '分析内容正在持续输出中……',
  'action_plan.placeholder.plan_unavailable.title': '计划内容不可用',
  'action_plan.placeholder.plan_unavailable.body': '今天没有返回可读取的计划内容。',
  'action_plan.placeholder.stopped': '生成已停止，你可以随时重新开始。',
  'action_plan.render.corrupted': 'Markdown 输出有残缺，已改为纯文本回退显示。',
  'action_plan.render.empty': '暂无内容。',

  'chat.header.title': '聊天',
  'chat.input_placeholder': '输入消息……',
  'chat.default_model': '选择模型',
  'chat.provider_unavailable': '当前没有可用服务商',
  'chat.powered_by': '由 {provider} 提供',
  'chat.cache_route_warning': '已切换线路，缓存不会跨供应商或模型复用。',
  'chat.clear': '清空',
  'chat.clear_title': '清空聊天记录',
  'chat.clear_confirm': '确认清空当前聊天记录？',
  'chat.clear_failed': '清空聊天失败：{error}',
  'chat.reasoning_title': '推理过程',
  'chat.thinking': '正在思考……',
  'chat.empty.with_context': '可以直接基于当前工作区上下文提问。',
  'chat.empty.without_context': '开始一段新的对话。',
  'chat.empty.followup': '你可以直接承接嵌入式上下文继续问。',
  'chat.empty.try_input': '可以先输入问题，或用语音开始。',
  'chat.record.start': '开始录音',
  'chat.record.stop': '停止录音',
  'chat.record.short_start': '录音',
  'chat.record.short_stop': '停止',
  'chat.record.active': '录音中 {value}',
  'chat.role.user': '我',
  'chat.role.assistant': 'AI',
  'chat.send_short': '发送',
  'chat.voice_model': '语音模型：{model}',
  'chat.transcribing': '正在转写……',
  'chat.transcription_failed': '没有识别到语音，请再试一次。',
  'chat.transcription_error': '语音转写失败：{error}',
  'chat.voice_config_error': '语音转写未配置。当前模型：{model}。请到设置 > 语音 Provider 配置。',
  'chat.microphone_error': '麦克风访问失败：{error}',

  'dashboard.title': '系统仪表盘',
  'dashboard.open_photos': '打开照片目录',
  'dashboard.open_screenshots': '打开截图目录',
  'dashboard.latest_photo': '最新照片',
  'dashboard.latest_screenshot': '最新截图',
  'dashboard.latest_photo_alt': '最新本地照片预览',
  'dashboard.latest_screenshot_alt': '最新桌面截图预览',
  'dashboard.media.show': '显示媒体',
  'dashboard.media.hide': '隐藏媒体',
  'dashboard.media.hidden': '媒体已隐私隐藏',
  'dashboard.media.hidden_detail': '需要检查最近采集内容时再手动显示。',
  'dashboard.camera_feed': '摄像头画面',
  'dashboard.no_data': '暂无数据',
  'dashboard.stat.cpu_usage': 'CPU 使用率',
  'dashboard.stat.memory': '内存',
  'dashboard.stat.memory_used': '已用 {percent}%',
  'dashboard.stat.disk_free': '磁盘剩余',
  'dashboard.stat.days_left': '约剩 {value} 天',
  'dashboard.stat.storage_used': '已用存储',
  'dashboard.stat.group_size': '约 {value} MB/组',
  'dashboard.stat.air_quality': '空气质量（US）',
  'dashboard.stat.loading': '加载中……',
  'dashboard.stat.focus_time': '专注时长',
  'dashboard.stat.away': '离开',
  'dashboard.stat.limit': '阈值：{value} 分钟',
  'dashboard.stat.timer_paused': '计时已暂停',
  'dashboard.alert.open_folder_failed': '打开目录失败：{error}',
  'dashboard.alert.network_error': '网络错误或后端不可达',
  'camera_feed.live_stream_alt': '实时摄像头画面',
  'camera_feed.ready': '摄像头已就绪',
  'camera_feed.show_stream': '摄像头已隐私隐藏',
  'camera_feed.disconnected': '摄像头未连接',
  'camera_feed.disable_detection': '关闭人体检测',
  'camera_feed.enable_detection': '开启人体检测',
  'camera_feed.detecting': '检测中',
  'camera_feed.detection_off': '关闭',
  'camera_feed.live': '实时',
  'camera_feed.ready_short': '就绪',
  'camera_feed.offline': '离线',

  'expense.title': '开销表',
  'expense.file': '文件',
  'expense.source': '来源',
  'expense.updated': '更新',
  'expense.sheets': 'Sheet 数',
  'expense.file_fallback': 'Balance Sheet.xlsx',
  'expense.refresh': '刷新',
  'expense.refreshing': '刷新中……',
  'expense.loading': '正在加载开销数据……',
  'expense.snapshot_kicker': '快照',
  'expense.snapshot_title': '当前财务快照',
  'expense.snapshot_description': '上面的数字只取程序运行时之前最近一次有效记录，作为下面趋势卡的摘要入口。',
  'expense.kpi.cash_and_stock': '现金及等价物',
  'expense.kpi.daily_burn': '最近日均支出',
  'expense.kpi.required_budget': '每月必须预算',
  'expense.kpi.coverage_days': '现金覆盖天数',
  'expense.kpi_hint.cash_and_stock': '以当前可见时间窗里的最新资产为准。',
  'expense.kpi_hint.daily_burn': '按程序运行时刻回溯到最近有效记录。',
  'expense.kpi_hint.required_budget': '从预算表汇总，不受未来开销行影响。',
  'expense.kpi_hint.coverage_days': '按最新资产和最近日均支出估算。',
  'expense.chart_eyebrow': '开销表',
  'expense.balance_chart_title': '资产与支出趋势',
  'expense.balance_chart_description': '把总资产、分账户资产和日均支出放回开销表主视图，直接看波动和支出压力。',
  'expense.balance_chart_unavailable': '当前暂时无法加载资产与支出图表。',
  'expense.forecast_title': '未来收入预测',
  'expense.forecast_desc': '预测行和实际历史分开处理，未来收入可以直接看见，但不会污染当前支出统计。',
  'expense.forecast_range': '预测区间',
  'expense.forecast_range_hint': '{count} 个月',
  'expense.forecast_fixed_income': '每月固定收入',
  'expense.forecast_fixed_income_hint': '按毕业月份前的基础收入填入。',
  'expense.forecast_extra_income': '每月额外收入',
  'expense.forecast_total_income': '每月收入合计',
  'expense.forecast_planned_spend': '每月计划支出',
  'expense.forecast_net_cash_flow': '每月计划净现金流',
  'expense.forecast_projected_balance': '预计期末现金+股票',
  'expense.error.load_chart': '加载资产图表失败',
  'expense.error.load_sheet': '加载开销表失败',
  'expense.error.chart_not_found': '未找到资产与支出图表',
  'expense.error.generic': '加载失败',
  'expense.recent_spending': '近期开销',
  'expense.recent_spending_desc': '优先显示最近有支出、备注或报销说明的记录。',
  'expense.period_spend': '期间支出 {value}',
  'expense.daily_average': '日均 {value}',
  'expense.large_spend': '大支出：{value}',
  'expense.income_note': '收入说明：{value}',
  'expense.no_recent_spending': '最近没有可展示的开销记录。',
  'expense.budget_structure': '预算结构',
  'expense.budget_structure_desc': '把固定预算和弹性预算拆开看，再按类别汇总。',
  'expense.monthly_required': '每月必须',
  'expense.monthly_optional': '每月弹性',
  'expense.per_month': '/ 月',
  'expense.no_budget': '预算表里还没有可用的预算项目。',
  'expense.high_value_assets': '高值资产',
  'expense.high_value_assets_desc': '保留大于 1000 元的资产条目，更适合看清单而不是财务分类。',
  'expense.quantity_price': '数量 {quantity} · 单价 {price}',
  'expense.total': '合计',
  'expense.no_assets': '资产表里还没有高值资产记录。',
  'expense.social': '人情支出',
  'expense.social_desc': '这部分是事件型支出，用紧凑列表比完整表格更合适。',
  'expense.no_date': '未记录日期',
  'expense.no_social': '暂无人情记录。',
  'expense.tips': '支出提示',
  'expense.tips_desc': '保留建议，但把它降级成辅助信息，不和核心指标抢位置。',
  'expense.no_tips': '当前没有额外提示。',
  'expense.raw_sheets': '原始工作表',
  'expense.raw_sheets_desc': '原始表格保留为详情视图，一次只看一个 sheet。',
  'expense.raw_sheets_aria': '原始工作簿工作表',
  'expense.raw_sheet_rows': '共 {count} 行{suffix}',
  'expense.raw_sheet_truncated': '（已截断）',
  'expense.days_value': '{value} 天',
  'expense.more_items': '还有 {count} 项',

  'plots.section.health.title': '健康主视图',
  'plots.section.health.desc': '先看体重、体脂和时间配置，快速判断健康行为有没有失衡。',
  'plots.section.performance.title': '行为与训练',
  'plots.section.performance.desc': '把跑步趋势和 HHH 节律放在一起看，更容易发现执行强度与恢复节奏。',
  'plots.section.other.title': '其他图表',
  'plots.section.other.desc': '保留未分组图表，避免数据缺失。',
  'plots.generated_none': '未生成',
  'plots.warning.title': '发现异常数据，相关图表已标注警告',
  'plots.warning.body': '请先修正原始表格，再执行“刷新图表”。未修正前，这些图表会继续提示异常。',
  'plots.warning.fallback_title': '异常数据',
  'plots.warning.jump': '跳转到 {chartId}',
  'plots.warning.show_details': '展开其余 {count} 条警告',
  'plots.warning.hide_details': '收起警告明细',
  'plots.inline_warning.title': '以下记录提取不完整，可能导致这张图出现断点',
  'plots.inline_warning.detail_fallback': '请检查源数据',
  'plots.inline_warning.remaining': '其余 {count} 条明细已省略，请看顶部异常面板。',
  'plots.chart.primary': '主图',
  'plots.chart.support': '辅助图',
  'plots.chart.warning': '警告',
  'plots.empty_chart': '暂无可用图表数据',
  'plots.hero.chip': '图表面板',
  'plots.hero.title': '先看最影响健康的图，再看辅助分析图',
  'plots.hero.desc': '这个页面按信息优先级重排：顶部先给总览与异常提示，中段放体重和时间配置主图，下段再放训练、HHH 和财务。',
  'plots.refresh': '刷新图表',
  'plots.refreshing': '刷新中……',
  'plots.summary.chart_count': '图表数量',
  'plots.summary.section_count': '分组数量',
  'plots.summary.warning_count': '警告数量',
  'plots.summary.generated_at': '最近生成',
  'plots.error_title': '图表加载失败',
  'plots.error_load': '加载图表失败。',
  'plots.empty': '暂无可显示的图表数据。',

  'project_progress.loading': '正在加载项目动量……',
  'project_progress.error.title': '数据加载失败',
  'project_progress.error.body': '项目进展加载失败，请确认后端已经启动。',
  'project_progress.retry': '重试',
  'project_progress.title': '项目动量',
  'project_progress.refresh': '刷新数据',
  'project_progress.active_focus': '当前重点（TODO）',
  'project_progress.no_pending': '目前没有待办任务，已经清空了。',
  'project_progress.overall_momentum': '整体动量',
  'project_progress.completed': '已完成',
  'project_progress.total_tasks': '跟踪任务总数：',
  'project_progress.completed_tasks': '已完成任务：',
  'project_progress.pending_tasks': '待办任务：',
  'project_progress.recent_milestone': '最近完成的里程碑',
  'project_progress.no_completed': '还没有已完成任务。',
  'project_progress.recent_activity': '最近活动（14 天）',
  'project_progress.no_commits': '最近 14 天没有新的提交。',

  'system_logs.title': '系统监控日志',
  'system_logs.subtitle': '实时后端事件流',
  'system_logs.empty': '暂无日志。',
  'system_logs.pause': '暂停',
  'system_logs.resume': '继续',
  'system_logs.copy_visible': '复制当前可见',
  'system_logs.copied': '当前可见日志已复制。',
  'system_logs.copy_failed': '剪贴板不可用。',
  'system_logs.search_placeholder': '搜索当前日志',
  'system_logs.filter.all': '全部',
  'system_logs.filter.error': '错误',
  'system_logs.filter.warning': '警告',
  'system_logs.filter.info': '信息',

  'usage.title': '用量面板',
  'usage.subtitle': '按记录会话汇总的历史模型消耗',
  'usage.window.all_time': '全部已记录调用',
  'usage.refresh': '刷新',
  'usage.error.load': '加载用量面板失败。',
  'usage.loading': '正在加载用量面板……',
  'usage.empty': '还没有记录到模型用量。',
  'usage.overview': '用量概览',
  'usage.total_caption': '当前跟踪会话累计记录的模型 Token 总量',
  'usage.latest_activity': '最近活动',
  'usage.prompt_share': 'Prompt 占比',
  'usage.completion_share': 'Completion 占比',
  'usage.summary.total_tokens': '总 Token',
  'usage.summary.prompt_tokens': 'Prompt Token',
  'usage.summary.completion_tokens': 'Completion Token',
  'usage.summary.completion_rate': 'Completion tok/s',
  'usage.summary.total_rate': '总 tok/s',
  'usage.summary.cache_hit': '缓存命中',
  'usage.summary.cache_hit_rate': '缓存命中率',
  'usage.summary.reasoning_tokens': '思考 Token',
  'usage.summary.active_sources': '活跃来源',
  'usage.summary.prompt_split': '{prompt} prompt / {completion} completion',
  'usage.summary.percent_of_total': '占总量 {value}',
  'usage.summary.completion_duration': 'Completion tokens / duration',
  'usage.summary.total_duration': 'Prompt + completion / duration',
  'usage.summary.cache_split': '{hit} 命中 / {miss} 未命中',
  'usage.summary.cache_hit_rate_detail': 'Prompt Token 缓存占比',
  'usage.summary.reasoning_tokens_detail': 'Provider 返回的思考 Token',
  'usage.summary.recorded_sessions': '记录会话 {value}',
  'usage.by_source': '按来源',
  'usage.by_source.empty': '当前没有来源用量。',
  'usage.source.total': '{value} 总计',
  'usage.source.sessions': '{value} 个会话',
  'usage.source.completed': '{value} 次完成',
  'usage.source.failed': '{value} 次失败',
  'usage.source.duration': '耗时 {value}',
  'usage.source.prompt_share': 'Prompt 占比 {value}',
  'usage.source.completion_share': 'Completion 占比 {value}',
  'usage.speed_trend.title': '速度趋势',
  'usage.speed_trend.subtitle': '按已完成调用统计的模型吞吐变化',
  'usage.speed_trend.axis_note': '高速模型可能使用右轴；tooltip 始终显示真实值。',
  'usage.speed_trend.empty': '暂无带耗时的已完成调用。',
  'usage.speed_trend.output_rate': '输出 tok/s',
  'usage.speed_trend.total_rate': '总 tok/s',
  'usage.speed_trend.high_speed_axis': '高速 tok/s',
  'usage.speed_trend.tooltip_source': '来源',
  'usage.speed_trend.tooltip_provider': 'Provider',
  'usage.speed_trend.tooltip_reasoning': '推理强度',
  'usage.speed_trend.tooltip_service_tier': '服务层级',
  'usage.speed_trend.tooltip_duration': '耗时',
  'usage.speed_trend.tooltip_tokens': 'Token',
  'usage.speed_trend.tooltip_cache': '缓存',
  'usage.speed_trend.tooltip_reasoning_tokens': '思考 Token',
  'usage.daily': '每日用量',
  'usage.daily.empty': '暂无每日用量。',
  'usage.daily.completed_failed': '{completed} 已完成 / {failed} 失败',
  'usage.recent_sessions': '最近会话',
  'usage.recent_sessions.empty': '暂无最近会话。',
  'usage.recent_calls': '最近调用',
  'usage.recent_calls.empty': '暂无最近调用。',
  'usage.cache_scope.session_total': '会话累计',
  'usage.cache_scope.single_request': '单次请求',
  'usage.label.prompt': 'Prompt',
  'usage.label.completion': 'Completion',
  'usage.label.total': '总计',
  'usage.label.cache_hit': '缓存命中',
  'usage.label.cache_miss': '缓存未命中',
  'usage.label.cache_hit_rate': '缓存命中率',
  'usage.label.reasoning_tokens': '思考 Token',
  'usage.label.service_tier': '服务层级',
  'usage.label.not_recorded': '未记录',
  'usage.label.completion_rate': '输出 tok/s',
  'usage.label.total_rate': '总 tok/s',
  'usage.label.total_rate_hint': '按请求耗时计算，包含 Prompt 与 Completion Token。',
  'usage.label.share': '占比',
  'usage.label.prompt_share': 'Prompt 占比',
  'usage.label.completion_share': 'Completion 占比',
  'usage.label.session': '会话',
  'usage.label.source': '来源',
  'usage.label.completed': '已完成',
  'usage.label.failed': '失败',
  'usage.label.last_status': '最后状态',
  'usage.label.last_call': '最后调用',
  'usage.label.call': '调用',
  'usage.label.status': '状态',
  'usage.label.model': '模型',
  'usage.label.provider': '供应商',
  'usage.label.duration': '耗时',
  'usage.label.started': '开始时间',
  'usage.label.unknown': '未知',
  'usage.status.completed': '已完成',
  'usage.status.failed': '失败',
  'usage.status.ignored': '无用量',
  'usage.status.started': '进行中',
  'usage.status.unknown': '未知',

  'face_history.title': '黑眼圈历史',
  'face_history.subtitle': '实时脉冲使用摄像头分数，历史图表使用已保存照片样本。',
  'face_history.camera_online': '在线',
  'face_history.camera_offline': '离线',
  'face_history.waiting_samples': '正在等待通过过滤的实时黑眼圈样本',
  'face_history.camera_offline_message': '摄像头离线',
  'face_history.live_camera_score': '实时摄像头分数',
  'face_history.live_pulse': '实时黑眼圈脉冲',
  'face_history.latest_score': '最新分数',
  'face_history.latest_time': '最新时间',
  'face_history.camera': '摄像头',
  'face_history.samples': '样本数',
  'face_history.trend_window': '趋势窗口',
  'face_history.average': '平均值',
  'face_history.no_trend': '暂无趋势数据',
  'face_history.live_chart_aria': '实时黑眼圈分数图',
  'face_history.trend_chart_aria': '{title}黑眼圈趋势图',
  'face_history.trend.day': '最近24小时',
  'face_history.trend.week': '最近7天',
  'face_history.trend.month': '最近30天',
  'face_history.trend.all': '全部历史',
  'face_history.no_image': '暂无图片',
  'face_history.score': '分数：{value}',
  'face_history.load_timeout': '加载最新报告时请求超时。',
  'face_history.analysis_failed': '人脸分析失败。',
  'face_history.export_failed': '导出失败：{error}',
  'face_history.unknown_error': '未知错误',
  'face_history.error_prefix': '错误：{error}',
  'face_history.loading_report': '正在加载黑眼圈分析报告……',
  'face_history.empty_title': '还没有分析报告。',
  'face_history.empty_body': '点击“立即分析”生成第一份缓存人脸报告。',
  'face_history.lightest': '最轻（状态最好）',
  'face_history.heaviest': '最重（状态最差）',
  'face_history.analyzing': '分析中……',
  'face_history.analyze_now': '立即分析',
  'face_history.export_excel': '导出 Excel',

  'onboarding.progress': '第 {current} / {total} 步',
  'onboarding.button.back': '返回',
  'onboarding.button.continue': '继续',
  'onboarding.button.finish': '完成设置',
  'onboarding.button.skip_chat': '先跳过聊天配置',
  'onboarding.button.choose_folder': '选择文件夹',
  'onboarding.field.display_language': '显示语言',
  'onboarding.field.provider_route': '服务路由',
  'onboarding.field.api_base_url': 'API Base URL',
  'onboarding.field.api_base_url_hint': '当前先保存到 onboarding 设置里，后续步骤再接到真实运行时路由。',
  'onboarding.field.api_key': 'API Key',
  'onboarding.field.model': '模型',
  'onboarding.field.launch_at_login': 'Windows 登录后自动启动 Vantage',
  'onboarding.field.import_legacy': '把现有历史记录导入打包版数据目录',
  'onboarding.field.selected_folder': '已选择目录',
  'onboarding.field.no_folder_selected': '还没有选择目录。',
  'onboarding.provider.openai': '兼容 OpenAI',
  'onboarding.provider.gemini': '兼容 Gemini',
  'onboarding.provider.custom': '自定义服务',
  'onboarding.welcome.eyebrow': '首次启动',
  'onboarding.welcome.title': '欢迎使用 Vantage',
  'onboarding.welcome.description': '这个初始化流程会把打包版需要的用户设置、聊天配置和历史导入都迁出源码目录。',
  'onboarding.welcome.bullet_1': '先确认打包版会把哪些内容放到用户数据目录。',
  'onboarding.welcome.bullet_2': '配置聊天服务，或者明确选择先跳过。',
  'onboarding.welcome.bullet_3': '旧仓库历史只导入一次，后续都使用打包版副本。',
  'onboarding.provider.eyebrow': '聊天配置',
  'onboarding.provider.title': '连接聊天服务',
  'onboarding.provider.description': '这些字段现在会保存到 providers.json 和 settings.json。真实后端消费后续再接，但 onboarding 已经会把值持久化。',
  'onboarding.provider.bullet_1': '服务路由、API 地址、API Key 和模型都会进入用户配置。',
  'onboarding.provider.bullet_2': '开机启动偏好也在这里保存，后续安装器步骤会真正应用。',
  'onboarding.provider.bullet_3': '即使跳过聊天配置，也不会阻塞你进入应用其他功能。',
  'onboarding.migration.eyebrow': '数据导入',
  'onboarding.migration.title': '把旧历史导入打包版数据',
  'onboarding.migration.description': '你可以选择把旧 history 目录迁到打包版用户数据目录。迁移只记录一次，同一个来源不会重复导入。',
  'onboarding.migration.bullet_1': '这里只复制历史和状态文件。',
  'onboarding.migration.bullet_2': '大体积照片和截图库仍保留在原来的位置。',
  'onboarding.migration.bullet_3': '如果同一个旧目录已经导入过，这一步会复用之前的迁移记录。',
  'onboarding.complete.eyebrow': '完成',
  'onboarding.complete.title': '写入初始化状态并打开应用',
  'onboarding.complete.description': '最后一步会保存 onboarding_completed、聊天配置和可选迁移状态。完成后，下次启动会直接进入主界面。',
  'onboarding.complete.bullet_1': 'settings.json 会记录 onboarding、开机启动和显示语言偏好。',
  'onboarding.complete.bullet_2': 'providers.json 会记录你输入的服务选择和密钥配置。',
  'onboarding.complete.bullet_3': 'migration-state.json 会记录旧历史来自哪里以及导入时间。',
  'onboarding.complete.summary_title': '即将写入的内容',
  'onboarding.complete.summary_language': '显示语言',
  'onboarding.complete.summary_chat': '聊天配置',
  'onboarding.complete.summary_chat_skipped': '本次先跳过',
  'onboarding.complete.summary_legacy_import': '旧数据导入',
  'onboarding.complete.summary_legacy_yes': '已启用',
  'onboarding.complete.summary_legacy_no': '已跳过',
  'onboarding.error.finish_failed': '完成初始化失败。',
};

export const DISPLAY_COPY = {
  'en-US': EN_US_COPY,
  'zh-CN': ZH_CN_COPY,
};

export function translate(language, key, replacements = {}) {
  const normalizedLanguage = DISPLAY_COPY[language] ? language : 'en-US';
  const template = DISPLAY_COPY[normalizedLanguage][key] ?? DISPLAY_COPY['en-US'][key] ?? key;

  return Object.entries(replacements).reduce(
    (message, [placeholder, value]) => message.replaceAll(`{${placeholder}}`, String(value)),
    template,
  );
}
